DEF_HELPER_FLAGS_4(sym_add_i32, TCG_CALL_NO_RWG_SE, ptr, i32, ptr, i32, ptr)
DEF_HELPER_FLAGS_4(sym_add_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64, ptr)
DEF_HELPER_FLAGS_4(sym_sub_i32, TCG_CALL_NO_RWG_SE, ptr, i32, ptr, i32, ptr)
DEF_HELPER_FLAGS_4(sym_sub_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64, ptr)

DEF_HELPER_FLAGS_4(sym_shift_right_i32, TCG_CALL_NO_RWG_SE, ptr, i32, ptr, i32, ptr)
DEF_HELPER_FLAGS_4(sym_shift_right_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64, ptr)
DEF_HELPER_FLAGS_4(sym_arithmetic_shift_right_i32, TCG_CALL_NO_RWG_SE, ptr, i32, ptr, i32, ptr)
DEF_HELPER_FLAGS_4(sym_arithmetic_shift_right_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64, ptr)
DEF_HELPER_FLAGS_4(sym_shift_left_i32, TCG_CALL_NO_RWG_SE, ptr, i32, ptr, i32, ptr)
DEF_HELPER_FLAGS_4(sym_shift_left_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64, ptr)

DEF_HELPER_FLAGS_3(sym_load_i64, TCG_CALL_NO_RWG_SE, ptr, i64, ptr, i64)
DEF_HELPER_FLAGS_3(sym_load_host_i64, TCG_CALL_NO_RWG_SE, ptr, ptr, i64, i64)
DEF_HELPER_FLAGS_5(sym_store_host_i64, TCG_CALL_NO_RWG, void, i64, ptr, ptr, i64, i64)
